# NumPy Array Operations

In [1]:
import numpy as np
np.random.seed(902)
arr = np.random.randint(0,101,10)

arr

array([66, 49, 29,  7, 38, 91, 39,  9, 56, 15])

In [2]:
arr2 = np.random.randint(0,101,10)
arr2

array([ 61, 100,  86,  26,  50,  22,  55,  39,   3,  12])

We are using the matrix below to try and isolate rows, columns and specific segments. This is a useful skill to learn when working with image arrays.

In [3]:
matrix = np.arange(0,100).reshape(10,10)
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

Isolate the second row of the matrix.

In [4]:
matrix[1,:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Isolate the second column of the matrix.

In [5]:
matrix[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

Isolate the top left corner of the matrix in a 3x3 array.

In [6]:
matrix[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

Now take our original matrix, if we want to change any of the values in the matrix this can also be completed using slicing. In this case I want to change the value for the first three rows to 0.

In [7]:
matrix = np.arange(0,100).reshape(10,10)
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

First I want to make sure I can isolate the first three rows.

In [8]:
matrix[0:3,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

Now I set the value to 0 on each row and output the matrix. This could be useful in pre-processing images to ignore non-relevant pixels.

In [9]:
matrix[0:3,:] = 0
matrix

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

Challenge: 

*   Try isolating the fifth row of the matrix.
*   Try isolating the seventh column of the matrix.
*   Try isolating the bottom right corner of the matrix in a 3x3 array.



In [10]:
matrix[4,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [11]:
matrix[:,6]

array([ 0,  0,  0, 36, 46, 56, 66, 76, 86, 96])

In [12]:
matrix[7:10,7:10]

array([[77, 78, 79],
       [87, 88, 89],
       [97, 98, 99]])